CREATE TABLE IF NOT EXISTS "public"."post" (
  "id" integer NOT NULL serial ,
  "title" varchar NOT NULL,
  "description" text NOT NULL,
  PRIMARY KEY ("id")
);


alter table "public"."post" alter column id ADD GENERATED BY DEFAULT AS IDENTITY;